// <auto-generated />
namespace ecommerceSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BrandSubCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BrandSubCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "202010260646192_BrandSubCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
